Repository prisma-korea/graphql-schema-generator, pull requests merged in 2021-12, with the labels that each got.

#1 Add minimal type conversion
  src/converters/__mocks__/scalerConverter.js
  src/converters/scalarConverter.test.ts
  src/converters/scalarConverter.ts
  src/converters/typeConverter.test.ts
  src/converters/typeConverter.ts
  src/converters/types.ts
Labels: feature

#2 Add addTypeModiflers
  src/converters/addTypeModifiers.test.ts
  src/converters/addTypeModifiers.ts
Labels: feature

#3 Support @id
  src/converters/convertScalar.test.ts
  src/converters/convertScalar.ts
Labels: feature

#4 Apply convertType, addTypeModifiers and remove formatType
  src/formatters/__mocks__/formatType.js
  src/formatters/formatField.test.ts
  src/formatters/formatField.ts
  src/formatters/formatType.test.ts
  src/formatters/formatType.ts
  src/transpile.test.ts
  src/transpile.ts
Labels: feature

#5 Fix bug that multiple rules are not applied correctly.
  src/converters/addTypeModifiers.test.ts
  src/converters/addTypeModifiers.ts
  src/converters/convertScalar.ts
  src/converters/rules/modifier.ts
  src/converters/types.ts
  src/transpile.test.ts
Labels: bugfix

#6 Add conversion from BigInt and Decimal
  src/converters/convertScalar.test.ts
  src/converters/rules/scalar.ts
Labels: feature

#7 Initial support for generating scalar
  src/__mocks__/store.js
  src/converters/convertScalar.test.ts
  src/converters/rules/scalar.ts
  src/converters/types.ts
  src/formatters/formatScalar.test.ts
  src/formatters/formatScalar.ts
  src/store.ts
  src/transpile.test.ts
  src/transpile.ts
Labels: feature

#8 Initial support for enum
  src/formatters/formatDefinition.test.ts
  src/formatters/formatDefinition.ts
  src/formatters/formatModel.test.ts
  src/formatters/formatModel.ts
  src/parse.ts
  src/transpile.test.ts
  src/transpile.ts
Labels: feature

#10 Remove store, add extractScalars
  src/__mocks__/store.js
  src/converters/convertScalar.test.ts
  src/converters/rules/scalar.ts
  src/store.ts
  src/transpile.ts
Labels: refactor

#11 Rename enum GraphQL -> SDL, Prisma -> PSL
  src/converters/addTypeModifiers.test.ts
  src/converters/convertScalar.test.ts
  src/converters/rules/scalar.ts
  src/converters/types.ts
  src/transpile.ts
Labels: refactor

#12 Fix adding type modifier to list type
  src/converters/addTypeModifiers.test.ts
  src/converters/rules/modifier.ts
  src/transpile.test.ts
Labels: bugfix

#14 Pack cjs & esm modules and expose graphql-schema-generator
  .gitignore
  .npmignore
  .vscode/settings.json
  README.md
  package.json
  prisma/generated/schema.graphql
  prisma/schema.prisma
  src/index.ts
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
Labels: enhancement

#16 Add minimal workflow with codecov
  .github/workflows/ci.yml
  README.md
  codecov.yml
Labels: 💨 ci

#17 Setup prettier
  .prettierrc.js
  package.json
  pnpm-lock.yaml
Labels: :star2: config

#18 Add diff test for development
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  src/diff/diff.test.ts
  src/diff/previous.cache
Labels: 🧪 test

#19 Add missing tests for better understanding
  src/transpile.test.ts
Labels: 🧪 test

#21 New linting rules and publish workflow
  .eslintignore
  .eslintrc.cjs
  .eslintrc.js
  .github/workflows/publish-package.yml
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
  src/converters/addTypeModifiers.test.ts
  src/converters/addTypeModifiers.ts
  src/converters/convertScalar.test.ts
  src/converters/convertScalar.ts
  src/converters/convertType.test.ts
  src/converters/convertType.ts
  src/converters/rules/modifier.ts
  src/converters/rules/scalar.ts
  src/converters/types.ts
  src/diff/diff.test.ts
  src/formatters/formatDefinition.test.ts
  src/formatters/formatDefinition.ts
  src/formatters/formatField.test.ts
  src/formatters/formatField.ts
  src/formatters/formatScalar.ts
  src/index.ts
  src/parse.test.ts
  src/parse.ts
  src/transpile.test.ts
  src/transpile.ts
  src/utils.ts
Labels: 💨 ci, ✍️ lint

#24 Update readme and schema for specifying output
  README.md
  prisma/schema.prisma
Labels: documentation

#25 Move extractScalars to extractors folder
  src/extractors/extractScalars.test.ts
  src/extractors/extractScalars.ts
  src/transpile.ts
Labels: enhancement, 🧪 test

#27 Convert @uniqie to ID if no @id exists.
  src/converters/addTypeModifiers.test.ts
  src/converters/addTypeModifiers.ts
  src/converters/convertScalar.test.ts
  src/converters/convertScalar.ts
  src/converters/convertType.test.ts
  src/converters/convertType.ts
  src/converters/rules/scalar.ts
  src/converters/types.ts
  src/extractors/extractId.test.ts
  src/extractors/extractId.ts
  src/store.test.ts
  src/store.ts
  src/transpile.test.ts
  src/transpile.ts
Labels: 🎯 feature

#28 Move extractId to rules/scalar
  src/converters/convertScalar.test.ts
  src/converters/rules/scalar.ts
  src/store.test.ts
  src/store.ts
  src/transpile.test.ts
  src/transpile.ts
Labels: 🍗 enhancement

#30 Add support for multiple @unique field
  src/converters/convertScalar.test.ts
  src/converters/rules/scalar.ts
  src/extractors/extractUniques.test.ts
  src/extractors/extractUniques.ts
Labels: bugfix

#33 Add generated comments to schema file
  src/transpile.test.ts
  src/transpile.ts
Labels: 🍗 enhancement

#40 Refactor using graphql utilities and generateGraphqlSchema
  package.json
  pnpm-lock.yaml
  prisma/generated/schema.graphql
  src/generateGraphqlSchema.test.ts
  src/generateGraphqlSchema.ts
  src/index.ts
  src/transpile.test.ts
  src/transpile.ts
  src/utils.ts
Labels: :wrench: refactor

#42 Support createQuery option.
  prisma/generated/schema.graphql
  prisma/schema.prisma
  src/__mocks__/transpile.js
  src/converters/types.ts
  src/diff/previous.cache
  src/generateGraphqlSchema.test.ts
  src/generateGraphqlSchema.ts
  src/index.ts
  src/transpile.test.ts
  src/transpile.ts
Labels: 🎯 feature

#44 Support createCRUD option
  prisma/generated/schema.graphql
  prisma/schema.prisma
  src/converters/types.ts
  src/diff/diff.test.ts
  src/diff/previous.cache
  src/generateGraphqlSchema.test.ts
  src/generateGraphqlSchema.ts
  src/transpile.test.ts
  src/transpile.ts
  src/utils.ts
Labels: 🎯 feature
